version: "2"

services:
 php-fpm:
    container_name: tabletennis-php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    image: quay.io/cashrewards/tabletennis:local
    volumes:
     - ./src:/var/www/html
     - ./node:/home/node/app
#    ports:
#     - "9001:9001"
    links:
      - mysql

 nginx:
    container_name: tabletennis-nginx
    image: nginx
    ports:
      - "90:80"
    links:
      - php-fpm
    volumes_from:
      - php-fpm:ro
        # from search-php-fpm container
        # /etc/nginx/conf.d/default.conf
        # /var/www/html [ image default = /usr/share/nginx/html ]

 mysql:
    container_name: tabletennis-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: tabletennis
      MYSQL_ROOT_PASSWORD: "<YourStrong!Passw0rd>"
    ports:
      - "3306:3306"
    logging:
      driver: none

 node:
    container_name: tabletennis-node
    image: "node:9"
#    user: "node"
#    volumes:
#     - ./src:/var/www/html
#    working_dir: /var/www/html
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
#    volumes:
#      - ./src-node/:/home/node/app
    links:
      - php-fpm
    volumes_from:
      - php-fpm:rw
    ports:
      - "8081:8081"
#    expose:
#      - "8081"
    command: "npm start"